# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_bit_obj <- function(bit_size) {
    .Call(`_exceedance_get_bit_obj`, bit_size)
}

set_bit_obj <- function(R_ptr, index) {
    invisible(.Call(`_exceedance_set_bit_obj`, R_ptr, index))
}

get_bit_count <- function(R_ptr) {
    .Call(`_exceedance_get_bit_count`, R_ptr)
}

print_bit <- function(R_ptr) {
    .Call(`_exceedance_print_bit`, R_ptr)
}

get_inter_number <- function(R_ptr1, R_ptr2) {
    .Call(`_exceedance_get_inter_number`, R_ptr1, R_ptr2)
}

get_list_inter_number <- function(bit_list, list_index, bit) {
    .Call(`_exceedance_get_list_inter_number`, bit_list, list_index, bit)
}

print_bit_list <- function(bit_list) {
    .Call(`_exceedance_print_bit_list`, bit_list)
}

C_get_range_by_bound <- function(R_sx, R_l, R_h) {
    .Call(`_exceedance_C_get_range_by_bound`, R_sx, R_l, R_h)
}

C_GW_compute_FDR <- function(sorted_i, R_H, R_L, rj_num, n) {
    .Call(`_exceedance_C_GW_compute_FDR`, sorted_i, R_H, R_L, rj_num, n)
}

